ropensci/roweb

- community/index.html
- packages/index.html
These packages have recently been transferred to @ropensci.
> List cartographer and internetarchive packages

- _posts/2015-03-10-introducing-wishlist.md
> Draft of the wishlist post

- packages/index.html
This commit adds the link to CRAN.
> Package internetarchive on CRAN

- packages/index.html
@sckott thanks for making rglobi update on webpage  - I've included two other minor tweaks in this pull request.
> added link to rglobi CRAN; removed early dev tag

- _posts/2015-06-03-baad.md
Except for the URL for Diego, these are all very minor formatting fixes. It's no problem if you can't incorporate them.
> URL for Diego plus some minor formatting issues

- CONTRIBUTING.md
- _posts/2015-09-23-rentrez-1-released.md
I also made a couple of tweaks to the CONTRIBUTING file, which I think got out of synch with the post layout? Check that my edits actually improve that file :smile:
> Blog post for rentrez version 1.0 release

- tutorials/spocc_tutorial.md
Already emailing with Scott Chamberlain about these sorts of additions. I noticed the spocc tutorial page was missing a reference to iDigBio so I went ahead and pasted some text.
> Update spocc tutorial to mention iDigBio

- index.html
Replaced `End to end reproducibility` with `End-to-end reproducibility`.
> Add hyphens

- _posts/2016-01-04-researcher-survey.md
Can you please a look and see if it reads ok? It's mostly to make sure that non Twitter users find this and respond.
> Added a blog post for the survey

- _drafts/2016-02-20-software-review.md
Continues #221. A few eyes would be nice.  This seems kind of dry.
> Update software review blog post

- _posts/2016-05-25-software-sustanability-ropensci.md
It's ready to go and I can post it today if there are no objections. 
@danielskatz @cboettig
> Added Dan's blog post

- _posts/2016-06-16-au-unconf.md
e.g, https://ropensci.org/blog/2016/06/16/www.microsoft.com.au to https://www.microsoft.com/en-au
> fix about 4 broken links

- _posts/2016-08-18-tokenizers-joins-ropensci.md
- community/index.html
- packages/index.html
> Blog post and listings for tokenizers

- _posts/technotes/2016-09-14-rdefra-release-033.md
Sorry, just needed to fix a typo in the title
> Fixed typo in title

- _posts/2016-10-28-comm-call-v12.md
Scott, Karthik, This is meant to be a blog post to introduce the next Community Call. Appreciate any comments/edits.
Improve the topic name?
Are the tags appropriate?
I'm waiting for Safia's title and for Titus to approve his bio.
> draft blog post for Community Call v12

- _posts/2016-11-09-ropensci-at-meetings.md
Plan is to do a post like this every 2-3 months.  
Please add relevant meetings in comments and I will include before posting Wed Nov 9, 3PM. Suggestions to improve intro para text, structure, (anything!) appreciated.
> draft blog post on rOpenSci team at conferences

- _posts/2016-11-16-tesseract.md
Post about tesseract and OCR in general. Work in progress.
> [WIP] tesseract post

- _posts/2017-01-10-xslt-release.md
Can you have a look @cboettig @sckott ? Thanks :)
> add post about xsd and xslt

- _drafts/2017-04-18-tabulizer.Rmd
- _drafts/2017-04-18-tabulizer.md
As requested, here is a draft of the post about tabulizer in both Rmd and md formats.
> Post about tabulizer

- _posts/2017-06-05-unconf_recap_1.md
This PR adds the first of our week long series of posts about the unconf. 4 projects/day.
> Added unconf recap post

- _posts/2017-06-09-unconf_recap_5.md
> Added last uconf post

- _posts/2017-06-12-ropensci_text_tools.md
- _posts/2017-06-14-ropensci_text_tools.md
An update on the rOpenSci text processing suite.
> add blog post about text packages

- _posts/2017-06-13-ropensci_text_tools.md
s/Procesing/Processing/ in post title
> fix typo in text blog title

- _posts/2017-06-02-unconf2017.md
- updated general unconf post by adding links to 5 projects posts
- changed `alt` tags to `title` to try to get photo credit visible on hover
> add projects posts, add title tags

- _drafts/2017-06-07-checkers.md
Post from team checkers!
Images are on imgur, could add them directly if you prefer.
> Submit checkers runconf post to queue

- _posts/2017-06-20-checkers.md
Added Molly Lewis as post author. No other changes
> add Molly author

- _drafts/2017-06-22-charlatan.Rmd
- _drafts/2017-06-22-charlatan.md
Now that `charlatan` is through review, here's a blog post
thoughts @noamross @stefaniebutland ?
> added charlatan blog post

- _posts/2017-06-27-packagemetrics.md
blog post on unconf17 `packagemetrics` project, ready to go live with 2017-06-27 date
> packagemetrics post from Becca Krouse unconf17

- _posts/2017-06-02-unconf2017.md
added links to posts on community, checkers, packagemetrics, to unconf17 general post. No other changes
> add new post links to unconf post

- _posts/2017-07-06-ropensci-fellowships.md
This is the fellowship post. Please post on Thursday. I will be offline till Tuesday the 11th. 🙏
> Added first version of fellowship post

- _drafts/2017-07-11-skimr.md
> @stefaniebutland here is a draft blog post!

- _drafts/2017-07-27-taxonomy-suite.Rmd
Changed the wording of a few sentences and added some detail on the intro to taxonomy. 
relates to issue #326
> Review of taxonomy blog post draft

- _posts/2017-06-02-unconf2017.md
added links to notary, webrockets and skimr posts near bottom of original unconf post
> update unconf post with new post links

- _posts/2017-06-02-unconf2017.md
added links to emldown, Roads Not Taken; grouped post links under Projects and Community
> add new unconf post links to old post

- _posts/technotes/2017-08-18-tesseract-16.md
Short tech note about tesseract update. I think this can be posted later today.
> Tech note about tesseract update

- _posts/2017-08-23-first-package-review.md
My blog post for the package review of `visdat`. The dummy link for getting to Nick's post is on line 39 (which it won't let me link to for some reason).
All feedback, edits, etc. welcome… 😳
> Mara/reviewer's half of the visdat 📦 review post

- _posts/2017-08-22-first-package-review.md
I literally misspelled the word package in the figure… 😵
> 😳 now with the word package spelled correctly

- fellowships/index.html
Merge at midnight Friday (or 12:01 Saturday).
This closes out the fellowship applications for 2017.
> DO NOT MERGE YET: Closing out the fellowships

- _posts/technotes/2017-09-07-spelling-release.md
Post about new spelling package.
> add post about spelling package

- _posts/technotes/2017-09-08-writexl-release.md
Short tech note announcing the new writexl package.
> brief tech note announcing writexl
